name: API Production Deployment
on:
  push:
    branches:
      - main
    paths:
      - api/**
jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PRODUCTION_URL_APP: "https://shopply.qdzungpham.com"
          envkey_PRODUCTION_URL_API: "https://api.shopply.qdzungpham.com"
          envkey_MONGO_URL: ${{ secrets.MONGO_URL }}
          envkey_SESSION_NAME: "shopply.qdzungpham.com.sid"
          envkey_SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          envkey_COOKIE_DOMAIN: "shopply.qdzungpham.com"
          directory: api
      - name: Build image
        run: |
          cd api
          docker build . --file Dockerfile --tag shopply-api --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/shopply-api
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag shopply-api $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Deploy Container to Digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: ${{ secrets.HOST_USER }}

          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/shopply-api
            # Change all uppercase to lowercase
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            # Strip "v" prefix from tag name
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
            # Use Docker `latest` tag convention
            [ "$VERSION" == "main" ] && VERSION=latest
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker pull $IMAGE_ID:$VERSION
            docker update --restart=no shopply-api || true
            docker stop shopply-api || true
            docker rm shopply-api || true
            docker run -e TZ=Australia/Brisbane -d --restart unless-stopped -p 8000:8000 --name shopply-api $IMAGE_ID:$VERSION
