name: app-prod-deployment
on:
  push:
    branches:
      - main
    paths:
      - web/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: go to folder
        run: cd web
      - name: create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_PRODUCTION_URL_APP=${{ secrets.NEXT_PUBLIC_PRODUCTION_URL_APP }} >> .env
      - name: Build image
        run: docker build . --file Dockerfile --tag shopply-app --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/shopply-app
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag shopply-app $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Deploy Container to Digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: ${{ secrets.HOST_USER }}

          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/shopply-app
            # Change all uppercase to lowercase
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            # Strip "v" prefix from tag name
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
            # Use Docker `latest` tag convention
            [ "$VERSION" == "main" ] && VERSION=latest
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker pull $IMAGE_ID:$VERSION
            docker update --restart=no shopply-app || true
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps -a -q) || true
            docker run -e TZ=Australia/Brisbane -d --restart unless-stopped -p 3000:3000 --name shopply-app $IMAGE_ID:$VERSION
